project:
  type: website
  output-dir: docs

website:
  title: "lab 6"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hyperparameter-tuning.qmd
        text: Lab 8

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    self-contained: true

editor: visual